export { default as Main } from './Main'
export { default as Mix } from './Mix'
export { default as MixResult } from './MixResult'
export { default as MixSelectMusic } from './MixSelectMusic'
export { default as MyMusic } from './MyMusic'
export { default as Playlist } from './Playlist'
export { default as PlaylistCreate } from './PlaylistCreate'
export { default as PlaylistEdit } from './PlaylistEdit'
export { default as PlaylistDetail } from './PlaylistDetail'
export { default as PlaylistSelectMusic } from './PlaylistSelectMusic'
export { default as Template } from './Template'
export { default as NotFound } from './NotFound'
export { default as Login } from './Login'
export { default as LoginSuccess }from './LoginSuccess'
export { default as Test } from './Test'
